### ISSUE TITLE
Issue with patient sub-hamburg01_T2star

### ISSUE THREAD

**Issue by andreanne-lemay** [ivadomed/data_example_spinegeneric#4]
The image sub-hamburg01_T2star.nii.gz has only one empty slice. Here is the error when trying to open it with fsleyes: 
![image](https://user-images.githubusercontent.com/49137243/87092132-ea9e6f00-c208-11ea-8107-0b1207846510.png)

The empty slice can be "observed" with itksnap

**Comment by charleygros** [comment]
Mmmm.. interesting ahah
I am going to swap this

**Comment by charleygros** [comment]
We decided to remove this file from the repo'.
Done in [768ca5f](https://github.com/ivadomed/data_spinegeneric_registered/commit/768ca5f307a0c6e7ff659762e86e1e6e33ad6f44).
